### ISSUE TITLE
Traceback using python 3.10

### ISSUE THREAD

**Issue by edy1192** [Vauxoo/travis2docker#138]
Traceback (most recent call last):
  File "/usr/local/bin/travisfile2dockerfile", line 5, in <module>
    from travis2docker.cli import main
  File "/home/user/.local/lib/python3.10/site-packages/travis2docker/cli.py", line 29, in <module>
    from .travis2docker import Travis2Docker
  File "/home/user/.local/lib/python3.10/site-packages/travis2docker/travis2docker.py", line 10, in <module>
    import jinja2
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 16, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/tests.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by luisg123v** [comment]
@edy1192 could you try updating jinja2, please?

**Comment by edy1192** [comment]
@luisg123v with jinja2-3.1.2 I got the same traceback.

**Comment by luisg123v** [comment]
I see jinja2 is under your local user environment, maybe you could fix it yourself. If that's the only Python 3.10 issue (lukely), that could work.

Just edit:

`/home/user/.local/lib/python3.10/site-packages/jinja2/tests.py`

And change:

`from collections import Mapping`

by:

`from collections.abc import Mapping`

Of course, this would be a temporary solution.

@ebirbe didn't this happen to you recently?

CC @moylop260
