### ISSUE TITLE
Error when cloning repo without .travis.yml file

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/travis2docker#188]
Since the `.travis.yml` file is not used anymore when using the `--deployv` option, it should be allowed for repos not having it.

If I run:

`travisfile2dockerfile --deployv git@git.vauxoo.com:vauxoo-dev/budget.git 14.0-rm_travis-luisg`

I get the following traceback:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/travisfile2dockerfile", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/travis2docker/cli.py", line 234, in main
    raise InvalidRepoBranchError(msg)
travis2docker.exceptions.InvalidRepoBranchError: The repo or the branch is incorrect value, because It can not got the .travis.yml or variables.sh content from git@git.vauxoo.com:vauxoo-dev/budget.git 14.0-rm_travis-luisg. 
Please, verify access repository,
verify exists url and revision, 
verify exists .travis.yml
```
```

In fact, I consider if the .travis file is not found but the variables file is, the `--deployv` option should be enabled, even if not provided. That because new projects will use that option by default.

**Comment by luisg123v** [comment]
CC @moylop260 @antonag32
